return {
    subter_fuge = {
        animationId = "rbxassetid://87482480949358",
        soundId = "rbxassetid://132297506693854",
        loops = false,
    },
    shucks = {
        animationId = "rbxassetid://74238051754912",
        soundId = "rbxassetid://123236721947419",
        loops = false,
    },
    silly_billy = {
        animationId = "rbxassetid://107464355830477",
        soundId = "rbxassetid://77601084987544",
        loops = false,
    },
    silly_billy_secret_version = {
        animationId = "rbxassetid://107464355830477",
        soundId = "rbxassetid://120176009143091",
        loops = false,
    },
    griddy = {
        animationId = "rbxassetid://93821902607346",
        soundId = "rbxassetid://0",
        loops = true,
    },
    wait = {
        animationId = "rbxassetid://119813505721636",
        soundId = "rbxassetid://123179402505565",
        loops = true,
    },
    so_retro = {
        animationId = "rbxassetid://90399490625732",
        soundId = "rbxassetid://81332555827290",
        loops = true,
    },
    subject_three = {
        animationId = "rbxassetid://75193609204744",
        soundId = "rbxassetid://136651893030423",
        loops = true,
    },
    distraction_dance = {
        animationId = "rbxassetid://98261071866527",
        soundId = "rbxassetid://0",
        loops = true,
    },
    poisoned = {
        animationId = "rbxassetid://83463199855585",
        soundId = "rbxassetid://118582448199737",
        loops = true,
    },
    pyt = {
        animationId = "rbxassetid://91362496118165",
        soundId = "rbxassetid://123571142022763",
        loops = true,
    },
    locked = {
        animationId = "rbxassetid://77920404652731",
        soundId = "rbxassetid://134957854576218",
        loops = true,
    },
    miss_the_quiet = {
        animationId = "rbxassetid://100986631322204",
        soundId = "rbxassetid://131936418953291",
        loops = true,
    },
    company_groove = {
        animationId = "rbxassetid://89926565466406",
        soundId = "rbxassetid://87037127480984",
        loops = true,
    },
	insanity = {
        animationId = "rbxassetid://75420633536507",
        soundId = "rbxassetid://125452574134166",
        loops = true,
    },
	hero = {
        animationId = "rbxassetid://133160365635320",
        soundId = "rbxassetid://114638282732720",
        loops = true,
    },
	headbanger = {
        animationId = "rbxassetid://103719006556178",
        soundId = "rbxassetid://0",
        loops = true,
    },
	california_girls_old = {
        animationId = "rbxassetid://121768360244671",
        soundId = "rbxassetid://96677274748910",
        loops = true,
    },
	bagup = {
        animationId = "rbxassetid://117853129871362",
        soundId = "rbxassetid://133954185831066",
        loops = true,
    },
	aol_guy = {
        animationId = "rbxassetid://80918082366233",
        soundId = "rbxassetid://101494406892555",
        loops = true,
    },
	cat_dance = {
        animationId = "rbxassetid://133145243088885",
        soundId = "rbxassetid://75850411329107",
        loops = true,
    },
	dio = {
        animationId = "rbxassetid://85856303945173",
        soundId = "rbxassetid://88954959076192",
        loops = false,
    },
	tick_tock = {
        animationId = "rbxassetid://118204083671442",
        soundId = "rbxassetid://79383274437776",
        loops = true,
    },
}
