return {
    NORMAL = {
        SLASH = "rbxassetid://116618003477002",
        CHICKEN = "rbxassetid://121781457295101",
    },
    JOHNWARD = {
        SLASH = "rbxassetid://97648548303678",
        CHICKEN = "rbxassetid://130578336615625",
    },
    BLOXY = {
        SLASH = "rbxassetid://110400453990786",
        CHICKEN = "rbxassetid://102343031936929",
    },
    BRIGHTEYES = {
        SLASH = "rbxassetid://98031287364865",
        CHICKEN = "rbxassetid://121781457295101",
    },
    HEARTBROKEN = {
        SLASH = "rbxassetid://119462383658044",
        CHICKEN = "rbxassetid://121781457295101",
    },
    SUNDERLAND = {
        SLASH = "rbxassetid://131696603025265",
        CHICKEN = "rbxassetid://107074146593306",
    },
    MILESTONE = {
        SLASH = "rbxassetid://77448521277146",
        CHICKEN = "rbxassetid://121781457295101",
    },
    RETRO = {
        SLASH = "rbxassetid://121255898612475",
        CHICKEN = "rbxassetid://89158177589094",
    },
    SKIES = {
        SLASH = "rbxassetid://122503338277352",
        CHICKEN = "rbxassetid://121781457295101",
    },
}
