return {
  ["TheForsakenLover3"] = true,
  ["vfjhfixvfk"] = true,
  ["aluucasha16"] = true,
  ["Rip_ZoroRoronoa700"] = true,
  ["Bearhunter360noscope"] = true,
  ["arsenalkingduh"] = true,
  ["Lobotomlc"] = true,
  ["unsurefrs"] = true,
  ["avoidinchildsupport"] = true,
  ["forsakenlover104"] = true,
  ["Starlix_27"] = true,
  ["NoobBoiAndBoi"] = true,
  ["Yesyes5244525"] = true,
  ["Rodionivao"] = true,
  ["TribunNews1945"] = true,
  ["NOBODYBEATMESUPER17"] = true,
  ["Cawoty2"] = true,
  ["c00lkid0178"] = true,
  ["42versus"] = true,
  ["pidarasina1223"] = true,
}
